# Generated by Django 5.2.1 on 2025-05-31 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='info/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SC', 'SnapChat'), ('IN', 'InstaGram'), ('WP', 'WhatsApp'), ('FB', 'FaceBook')], max_length=2)),
            ],
        ),
    ]
